backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "aboutus"
    label: "About Us"
    files:
      - file: "src/pages/about-us/index.md"
        label: "About Us"
        name: "aboutus"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "village-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: linkTitle, widget: string },
                  { label: Text, name: linkText, widget: text },
                  { label: Url, name: url, widget: string },
                ],
            }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }

  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "about-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Header Image", name: headerImage, widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "samsvillage"
    label: "Sams Village"
    files:
      - file: "src/pages/projects/sams-village/index.md"
        label: "Sams Village"
        name: "samsvillage"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "village-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Videos", name: "videos", widget: "markdown" }
          - {
              label: "Photos",
              name: gallery,
              widget: list,
              fields:
                [
                  { label: Photo, name: photo, widget: image },
                  { label: Alt text, name: alt, widget: string },
                ],
            }
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: linkTitle, widget: string },
                  { label: Photo, name: photo, widget: image },
                  { label: Text, name: linkText, widget: text },
                  { label: Url, name: url, widget: string },
                ],
            }
      - file: "src/pages/projects/sams-village/training-programme/index.md"
        label: "Training Programme"
        name: "trainingprogramme"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/projects/sams-village/library/index.md"
        label: "Library"
        name: "library"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/projects/sams-village/permaculture/index.md"
        label: "Permaculture"
        name: "permaculture"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }  
      - file: "src/pages/projects/sams-village/building-programme/index.md"
        label: "Building programme"
        name: "buildingprogramme"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }   
      - file: "src/pages/projects/sams-village/biogas/index.md"
        label: "Biogas"
        name: "biogas"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }   
      - file: "src/pages/projects/sams-village/njewa-new-office/index.md"
        label: "Njewa New Office"
        name: "njewanewoffice"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }                                        

  - name: "water"
    label: "Water"
    files:
      - file: "src/pages/projects/water/index.md"
        label: "Water"
        name: "water"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "water-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Photos",
              name: gallery,
              widget: list,
              fields:
                [
                  { label: Photo, name: photo, widget: image },
                  { label: Alt text, name: alt, widget: string },
                ],
            }
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: linkTitle, widget: string },
                  { label: Photo, name: photo, widget: image },
                  { label: Text, name: linkText, widget: text },
                  { label: Url, name: url, widget: string },
                ],
            }
      - file: "src/pages/projects/water-and-sanitation/index.md"
        label: "Water and sanitation"
        name: "waterandsanitation"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" } 
      - file: "src/pages/projects/water-boreholes/index.md"
        label: "Water boreholes"
        name: "waterboreholes"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }  
      - file: "src/pages/water/sanitation/index.md"
        label: "Sanitation"
        name: "sanitation"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }   
          
  - name: "health"
    label: "Health"
    files:
      - file: "src/pages/health/index.md"
        label: "Health"
        name: "health"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "health-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Photos",
              name: gallery,
              widget: list,
              fields:
                [
                  { label: Photo, name: photo, widget: image },
                  { label: Alt text, name: alt, widget: string },
                ],
            }
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: linkTitle, widget: string },
                  { label: Photo, name: photo, widget: image },
                  { label: Text, name: linkText, widget: text },
                  { label: Url, name: url, widget: string },
                ],
            }
      - file: "src/pages/projects/bicycle-ambulances/index.md"
        label: "Bicycle ambulances"
        name: "bicycleambulances"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" } 
      - file: "src/pages/health/disability/index.md"
        label: "Disability"
        name: "disability"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }  
      - file: "src/pages/health/hivaids/index.md"
        label: "hiv  / aids"
        name: "hivaids"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }   
      - file: "src/pages/projects/feeding-programme-in-schools/index.md"
        label: "Feeding programmes"
        name: "feedingprogrammes"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }  
      - file: "src/pages/projects/maternity-unit/index.md"
        label: "Maternity unit"
        name: "maternityunit"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-gallery",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }   
          - {
              label: "Photos",
              name: gallery,
              widget: list,
              fields:
                [
                  { label: Photo, name: photo, widget: image },
                  { label: Alt text, name: alt, widget: string },
                ],
            }   
      - file: "src/pages/projects/distributions/index.md"
        label: "Distributions"
        name: "distributions"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }                               

- name: "educatin"
    label: "Education"
    files:
      - file: "src/pages/education/index.md"
        label: "Education"
        name: "education"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "education-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: heroImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }          
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: linkTitle, widget: string },
                  { label: Photo, name: photo, widget: image },
                  { label: Text, name: linkText, widget: text },
                  { label: Url, name: url, widget: string },
                ],
            } 
      - file: "src/pages/projects/community-based-childcare-centres-cbccs/index.md"
        label: "CBCCs"
        name: "cbccs"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: headerImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }                       