---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/pages/index.md
  label: Latest news box
- type: directory
  path: src/pages/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: src/pages/news
  label: News
  create: all
  match: "**/*"
  templates:
  - news
- type: directory
  path: src/pages/shop
  label: Shop
  create: all
  match: "**/*"
  templates:
  - shop-product
- type: directory
  path: src/pages/about-us
  label: About Us
  create: all
  match: "**/*"
- type: directory
  path: src/pages/environment
  label: Environment
  create: all
  match: "**/*"
- type: directory
  path: src/pages/health
  label: Health
  create: all
  match: "**/*"
- type: directory
  path: src/pages/water
  label: Water
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
