---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: News and Events
- type: directory
  path: src/pages/events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: src/pages/news
  label: News
  create: all
  match: "**/*"
  templates:
  - news
- type: heading
  label: Homepage & Shop
- type: document
  path: src/pages/index.md
  label: Homepage
- type: directory
  path: src/pages/shop
  label: Shop
  create: all
  match: "**/*"
  templates:
  - shop-product
- type: heading
  label: All other pages
- type: directory
  path: src/pages/about-us
  label: About Us
  create: all
  match: "**/*"
- type: document
  path: src/pages/celebrate-and-give/index.md
  label: Celebrate and Give
- type: document
  path: src/pages/education/index.md
  label: Education
- type: directory
  path: src/pages/environment
  label: Environment
  create: all
  match: "**/*"
- type: directory
  path: src/pages/get-involved
  label: Get Involved
  create: all
  match: "**/*"
- type: directory
  path: src/pages/health
  label: Health
  create: all
  match: "**/*"
- type: document
  path: src/pages/our-work/index.md
  label: Our Work
- type: directory
  path: src/pages/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: src/pages/water
  label: Water
  create: all
  match: "**/*"
- type: document
  path: src/pages/why-malawi/index.md
  label: Why Malawi?
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_WEBPACK_PUBLICPATH=/
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
